image: Visual Studio 2019
version: 4.0.{build}
platform: "Any CPU"
configuration: Release

# before_build:
# - nuget restore

build_script:
  - cmd: PowerShell -Version 4.0 .\build.ps1 %APPVEYOR_BUILD_VERSION%

after_build:
  - appveyor PushArtifact artifacts\Seq.App.YouTrack.%APPVEYOR_BUILD_VERSION%.nupkg
